name: Help Wanted
labels: help wanted
assignees: ezbooz


title: "[HELP] "
description: If you encounter any issues, please describe them here
body:
  - type: dropdown
    id: dropdown-0
    attributes:
      label: Specify the version of the game
      options:
        - Steam
        - Official Client
        - Epicgames and others
      default: 0  # Steam is the first option (index 0)
  - type: textarea
    id: textarea-0
    attributes:
      label: What happened?
      description: Describe what happened in detail
      placeholder: "Enter a detailed description of the issue"
  - type: textarea
    id: textarea-1
    attributes:
      label: Game Log File (Optional)
      description: |
        Please provide the game log file located at: game_path/logs/client.txt. 
        This will help us diagnose your issue. You can attach the file manually to this issue.
      placeholder: "Provide the log file details here"
